### ISSUE TITLE
Get JIRA license for Open Source

### ISSUE THREAD

**Issue by cricketsloan** [BD2KGenomics/platform-administration#17]
There is an application that needs filling out.  If we do not quality, we may not be able to afford JIRA.

**Comment by cricketsloan** [comment]
Here is the application
https://www.atlassian.com/software/views/open-source-license-request


Here are my answers so far:

Computational Genomics Platform

https://cgp.genomics.ucsc.edu/

The Computational Genomics Lab is a shared venture
led by faculty, research scientists and engineers within the
UC Santa Cruz Genomics Institute.  It is a collection of Open Source Projects that a for the Genomics Community.

https://ucsc-cgl.atlassian.net/

We are an academic institution. 

Open Source Licence MISSING

https://github.com/DataBiosphere


Nadine Grassner

ngassner@ucsc.edu

UC Santa Cruz Genomics Institute , Engineering 2
University of California
95064


-----------------------------------------------------------------------
Stalling points

1) Which repo to use
2) I don't see easily accessible license information
3) JIRA is not set up so that anonymous can create a ticket

**Comment by cricketsloan** [comment]
Example of license

**Comment by natanlao** [comment]
This issue was moved to DataBiosphere/administration#84
