### ISSUE TITLE
write pipeline as leader autoscaling document

### ISSUE THREAD

**Issue by cricketsloan** [BD2KGenomics/platform-administration#21]
Write a document that describes the requirements for making the Toil leader the same as the running pipeline. An example of this is the latest commit to the Toil RNA-Seq pipeline.
BD2KGenomics/toil-rnaseq@a32acc3

BD2KGenomics/toil-rnaseq#139

**Comment by cricketsloan** [comment]
moved from: https://github.com/BD2KGenomics/core-operations/issues/147

**Comment by natanlao** [comment]
This issue was moved to DataBiosphere/administration#85
