### ISSUE TITLE
Integration tests to bring up dcc-ops

### ISSUE THREAD

**Issue by cricketsloan** [BD2KGenomics/platform-administration#25]
When there is a new release of a component TravisCI will bring up a dcc-ops infrastructure, onboard data and run pipeline tests

**Comment by cricketsloan** [comment]
This is moved from: https://github.com/BD2KGenomics/core-operations/issues/131

**Comment by cricketsloan** [comment]
I heard that this was complete.

**Comment by natanlao** [comment]
Kamino closed and cloned this issue to BD2KGenomics/dcc-ops
