### ISSUE TITLE
Define/design KC2 GUID use by Team Calcium

### ISSUE THREAD

**Issue by mikebaumann** [BD2KGenomics/platform-administration#6]
This includes:
- [ ] Determining which KC2-compliant GUIDs we will use at UCSC and within Team Calcium
- [ ] Briefly documenting (1-2 pages) the UCSC / Team Calcium flow, the types of ids (cloud URLs, UUID+version, DOS URLs, KC-2 GUIDs) that will be available/used within the flow, and a brief description of the implementation phases. This can then be reviewed within UCSC, then Team Calcium.

**Comment by david4096** [comment]
https://github.com/dcppc/data-stewards/issues/1

**Comment by mikebaumann** [comment]
Hi @david4096, will you provide an update on the progress/status here? Thanks!

**Comment by mikebaumann** [comment]
Draft out for review to our team by EOD tomorrow.

**Comment by cricketsloan** [comment]
We spoke today about how this could be modeled with eventually UCSC providing the dois or the minID's for the whole Data Commons by minting them and providing a stable DOS to resolve them .

The goal is to have a 2 page design and Brian would like a demo with just a few items.

**Comment by david4096** [comment]
Please check out the latest state of this in the `diagrams` branch https://github.com/david4096/identifier-interoperability/blob/diagrams/README.md !

I'll be moving ahead with merging this https://github.com/david4096/identifier-interoperability/pull/6 but would appreciate early review as we develop our strategy for working with GUID services.

Note, related to the demo, the plan is Use Case 1 of the linked document.

**Comment by cricketsloan** [comment]
Michael being added as he is the likely candidate for reviewing

**Comment by david4096** [comment]
Repo moved https://github.com/DataBiosphere/identifier-interoperability

**Comment by david4096** [comment]
Can we close this and open a new one?

Working on a new DOS that can be used to add GUIDs to the azul-index, which serves boardwalk.

https://github.com/DataBiosphere/dos-azul-lambda
